name: meherinMart
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.7+8

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  html: ^0.15.6
  dartz: ^0.10.1

  # Core
  cupertino_icons: ^1.0.8
  http: ^1.1.2
  meta: ^1.16.0
  collection: ^1.19.1
  crypto: ^3.0.6

  # State Management
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  provider: ^6.0.0
  equatable: ^2.0.7

  # UI & UX
  google_fonts: ^6.2.1
  iconsax: ^0.0.8
  hugeicons: ^0.0.7
  lottie: ^3.1.2
  shimmer: ^3.0.0
  toastification: ^3.0.2
  animated_custom_dropdown: ^3.1.1
  flutter_typeahead: ^5.2.0
  dotted_border: ^3.1.0
  cached_network_image: ^3.4.0

  # Desktop-specific
  window_manager: ^0.5.1
  screen_retriever: ^0.2.0

  # Database & Storage
  shared_preferences: ^2.5.3
  path_provider: ^2.1.3

  # Connectivity
  connectivity_plus: ^6.1.3

  # Media, Files & Printing
  image_picker: ^1.1.2
  pdf: ^3.11.3
  printing: ^5.14.2
  barcode_widget: ^2.0.4
  url_launcher: ^6.2.2

  # Charts & Forms
  fl_chart: ^0.71.0

  flutter_dotenv: ^6.0.0
  logger: ^2.6.1
  phone_form_field: ^10.0.8
  flutter_date_range_picker: ^0.2.1
  dio: ^5.9.0
  date_format: ^2.0.9
  init: ^1.0.0
  flutter_secure_storage: ^10.0.0
  easy_localization: ^3.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/jsons/
    - assets/icons/
    - assets/translations/
    - .env

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 900

    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
